# syntax=docker/dockerfile:1.25.0@sha256:0adf442eae370b6087e08edc7c50b552d80ddf261576f4ebd6421006b2461f12
FROM scratch AS ctx
COPY build-phases/ /
COPY lib/ /lib/
COPY modules/ /modules/

FROM quay.io/fedora/fedora-bootc:44

# ---- BEGIN GENERATED (build phases and modules; see scripts/gen-containerfile.sh) ----
# ---- END GENERATED ----

COPY cosign.pub /etc/pki/containers/cosign.pub

COPY --from=ctx /lib/validate-image.sh /usr/libexec/validate-image.sh
RUN bootc container lint
RUN /usr/libexec/validate-image.sh
