#!/bin/bash
set -eu

mount -o remount,rw /boot
trap 'mount -o remount,ro /boot' EXIT

if [ -d /sys/firmware/efi ]; then
    GRUB_CFG="/etc/grub2-efi.cfg"
else
    GRUB_CFG="/etc/grub2.cfg"
fi

grub2-mkconfig -o "$GRUB_CFG"
